### ISSUE TITLE
Action buttons

### ISSUE THREAD

**Issue by hecto932** [mayela/rock-paper-scissors#2]
![image](https://user-images.githubusercontent.com/5354758/66106621-266a2100-e573-11e9-8aa6-0e14ebcb3b22.png)

Me gusta como importaste varios recursos y utilizas el mismo componente para mostrar diferentes representaciones del botón.

Ahora viene lo bueno.

![image](https://user-images.githubusercontent.com/5354758/66106779-8fea2f80-e573-11e9-8935-14ea41014fba.png)

- Actualmente el componente `Option` es solo un tag `<img />`, no esta mal, pero piensa que esas imágenes tendrán acciones en el futuro. Podrías envolverlas en otro tag o ver si es posible usar eventos de clics sobre la misma imagen.

Por ahora agregales un evento de click a cada boton y que me imprima por consola la jugada que representa segun su imagen.

**Comment by mayela** [comment]
Resolved!
